[versions]
kotlin = "2.4.20"
paper = "26.3.build.159-beta"
shadow = "9.6.1"

[libraries]
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper" }

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }